[mds-ingest-service] Add getTripEvents service method to mds-ingest-service
lacuna-tech/mds-core pull request #717
Opened 2021-09-01 20:42 UTC by avatarneil

## 📚 Purpose
PR #709 added the repo method, this PR adds the service method.

## 📦 Impacts:
- mds-ingest-service

2021-09-01 20:48 UTC, BigIdeas approved these changes

2021-09-01 21:33 UTC, nessur commented
add a test please :)

2021-09-01 21:34 UTC, nessur requested changes
at least 1 test :)

2021-09-02 19:25 UTC, janedotx approved these changes

2021-09-07 16:15 UTC, nessur approved these changes

2021-09-07 16:41 UTC, merged